Configure wxWidgets with --disable-mediactrl. Fixes build on latest macOS / Xcode.
I was getting the following error when building wxWidgets on macOS 10.12.1 / Xcode 8.1:
    ../src/osx/cocoa/mediactrl.mm:76:10: fatal error: 'QTKit/QTKit.h' file not found
QTKit has apparently been deprecated for a while and was finally removed.